spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
  application:
    name: hello-server
eureka:
  instance:
    instance-id: hello-server
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka
info: 
  desc: Spring Cloud Hello World Dev
---
spring:
  profiles: test
  application:
    name: hello-server
eureka:
  instance:
    instance-id: hello-server
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka
info: 
  desc: Spring Cloud Hello World Test
